### ISSUE TITLE
大神，导出后格式不对呢

### ISSUE THREAD

**Issue by beclass** [azl397985856/file-writer#1]
导出的.csv  并没有按逗号 分列，全在一行了呢

**Comment by azl397985856** [comment]
贴下你的代码看看

**Comment by beclass** [comment]
就是按照例子来的
 writer('a.csv', '\
      year,age,status,sex,population\r\n\
      1850,20,0,1,1017281\r\n\
      1850,20,0,2,1003841\r\n\
      ','utf-8')

**Comment by azl397985856** [comment]
你是通过什么打开的？看到的在一行，你的代码我直接在console运行是正常的啊

**Comment by beclass** [comment]
mac  excel
