### ISSUE TITLE
write有返回文件流给我吗

### ISSUE THREAD

**Issue by zhangwei900808** [azl397985856/file-writer#2]
writer(`${name}的简历.html`, html, 'utf-8')
我现在有个需求：不下载文件，但是会生成文件流给我，我再传到后台，其实算是拓展功能了，能实现吗

**Comment by azl397985856** [comment]
能是肯定能。 不过已经超过了这个库的功能了。为什么这么说呢？
本质上file-writer的功能是你给我文件流或者文件内容，我给你生成文件。
而你的这个需求正好相反，是你给我文件，我给你文件流。

这个库的功能就是`前端下载文件`.

至于上传属于别的功能，你可以结合使用别的封装好的库。这里推荐一个vue的文件上传库[vue-filepond](https://github.com/pqina/vue-filepond)
